name: Build

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ master ]

env:
  RUST_TEST_THREADS: 1

jobs:
  # This job downloads and stores `cross` as an artifact, so that it can be
  # redownloaded across all of the jobs. Currently this copied pasted between
  # `ci.yml` and `deploy.yml`. Make sure to update both places when making
  # changes.
  install-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          depth: 50
      - uses: XAMPPRocky/get-github-release@v1
        id: cross
        with:
          owner: rust-embedded
          repo: cross
          matches: ${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: cross-${{ matrix.platform }}
          path: ${{ steps.cross.outputs.install_path }}
    strategy:
      matrix:
        platform: [ linux-musl, apple-darwin ]

  windows:
    runs-on: windows-latest
    # Windows technically doesn't need this, but if we don't block windows on it
    # some of the windows jobs could fill up the concurrent job queue before
    # one of the install-cross jobs has started, so this makes sure all
    # artifacts are downloaded first.
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 50
      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
        shell: bash
      - run: ci/build.bash cargo ${{ matrix.target }}
        shell: bash
      - run: ci/test.bash cargo ${{ matrix.target }}
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        channel: [ stable ]
        target:
          # MSVC
          - x86_64-pc-windows-msvc

  macos:
    runs-on: macos-latest
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 50

      - uses: actions/download-artifact@v1
        with:
          name: cross-apple-darwin
          path: /usr/local/bin/

      - run: chmod +x /usr/local/bin/cross

      - name: Do we need GNU tar? # Fix for macOS caching, https://github.com/actions/cache/issues/403
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH

      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - run: ci/build.bash cross ${{ matrix.target }}
        # Only test on macOS platforms since we can't simulate the others.
      - run: ci/test.bash cross ${{ matrix.target }}
        if: matrix.target == 'x86_64-apple-darwin'

    strategy:
      fail-fast: true
      matrix:
        channel: [ stable ]
        target:
          # macOS
          - x86_64-apple-darwin

  linux:
    runs-on: ubuntu-latest
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 50

      - name: Install dependencies
        run: |
          sudo apt update \
          && sudo apt upgrade \
          && sudo apt install libxkbcommon-dev \
          && sudo apt install libxcb-shape0-dev \
          && sudo apt install libxcb-xfixes0-dev

      - run: ci/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}

      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
    strategy:
      fail-fast: true
      matrix:
        channel: [ stable ]
        target:
          # Linux
          - x86_64-unknown-linux-gnu
